spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/employee-db
    username: postgres
    password: 1awd35zp
    driver-class-name: org.postgresql.Driver
  security:
    user:
      name: nimsika
      password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: "5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437"
  expiration: 300000
  issuer: "employee-management-system"
  audience: "employee-client"
  secret-base64: "c2VjcmV0LWtleS1mb3Itand0LWF1dGhlbnRpY2F0aW9uLXdpdGgtMzItYnl0ZXM="

